echo "Executing \"badexample00.txt\""
go run . "test/badexample00.txt"
echo "Executing \"badexample01.txt\""
go run . "test/badexample01.txt"
echo "Executing \"exeaple00.txt\""
go run . "test/example00.txt"
echo "Executing \"example01.txt\""
go run . "test/example01.txt"
echo "Executing \"example02.txt\""
go run . "test/example02.txt"
echo "Executing \"example03.txt\""
go run . "test/example03.txt"
echo "Executing \"example04.txt\""
go run . "test/example04.txt"
echo "Executing \"example05.txt\""
go run . "test/example05.txt"
echo "Executing \"example06.txt\""
go run . "test/example06.txt"
echo "Executing \"example07.txt\""
go run . "test/example07.txt"